// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: v1/notification.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPersonalizedEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []*InfoPersonalizedRequest `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
}

func (x *SendPersonalizedEmailRequest) Reset() {
	*x = SendPersonalizedEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPersonalizedEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPersonalizedEmailRequest) ProtoMessage() {}

func (x *SendPersonalizedEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPersonalizedEmailRequest.ProtoReflect.Descriptor instead.
func (*SendPersonalizedEmailRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendPersonalizedEmailRequest) GetEmails() []*InfoPersonalizedRequest {
	if x != nil {
		return x.Emails
	}
	return nil
}

type InfoPersonalizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email   string       `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name    string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject string       `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Detail  *DetailEmail `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *InfoPersonalizedRequest) Reset() {
	*x = InfoPersonalizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoPersonalizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoPersonalizedRequest) ProtoMessage() {}

func (x *InfoPersonalizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoPersonalizedRequest.ProtoReflect.Descriptor instead.
func (*InfoPersonalizedRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *InfoPersonalizedRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InfoPersonalizedRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoPersonalizedRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InfoPersonalizedRequest) GetDetail() *DetailEmail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type DetailEmail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text       string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Attachment [][]byte `protobuf:"bytes,2,rep,name=attachment,proto3" json:"attachment,omitempty"`
}

func (x *DetailEmail) Reset() {
	*x = DetailEmail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetailEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailEmail) ProtoMessage() {}

func (x *DetailEmail) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailEmail.ProtoReflect.Descriptor instead.
func (*DetailEmail) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *DetailEmail) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DetailEmail) GetAttachment() [][]byte {
	if x != nil {
		return x.Attachment
	}
	return nil
}

type SendCommonEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emails []*InfoCommonRequest `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	Detail *DetailEmail         `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *SendCommonEmailRequest) Reset() {
	*x = SendCommonEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_notification_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendCommonEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommonEmailRequest) ProtoMessage() {}

func (x *SendCommonEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommonEmailRequest.ProtoReflect.Descriptor instead.
func (*SendCommonEmailRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendCommonEmailRequest) GetEmails() []*InfoCommonRequest {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *SendCommonEmailRequest) GetDetail() *DetailEmail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type InfoCommonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email   string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *InfoCommonRequest) Reset() {
	*x = InfoCommonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_notification_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoCommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoCommonRequest) ProtoMessage() {}

func (x *InfoCommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoCommonRequest.ProtoReflect.Descriptor instead.
func (*InfoCommonRequest) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *InfoCommonRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InfoCommonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfoCommonRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_notification_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_notification_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_v1_notification_proto protoreflect.FileDescriptor

var file_v1_notification_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x60, 0x0a, 0x1c, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x17, 0x49,
	0x6e, 0x66, 0x6f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0x41, 0x0a, 0x0b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d,
	0x65, 0x6e, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a,
	0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0x57, 0x0a, 0x11, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x65, 0x6e,
	0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xe5, 0x01, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6c,
	0x0a, 0x15, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2d, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x0f,
	0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x27, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x61,
	0x6c, 0x73, 0x72, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_notification_proto_rawDescOnce sync.Once
	file_v1_notification_proto_rawDescData = file_v1_notification_proto_rawDesc
)

func file_v1_notification_proto_rawDescGZIP() []byte {
	file_v1_notification_proto_rawDescOnce.Do(func() {
		file_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_notification_proto_rawDescData)
	})
	return file_v1_notification_proto_rawDescData
}

var file_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_notification_proto_goTypes = []interface{}{
	(*SendPersonalizedEmailRequest)(nil), // 0: notification.v1.SendPersonalizedEmailRequest
	(*InfoPersonalizedRequest)(nil),      // 1: notification.v1.InfoPersonalizedRequest
	(*DetailEmail)(nil),                  // 2: notification.v1.DetailEmail
	(*SendCommonEmailRequest)(nil),       // 3: notification.v1.SendCommonEmailRequest
	(*InfoCommonRequest)(nil),            // 4: notification.v1.InfoCommonRequest
	(*SendEmailResponse)(nil),            // 5: notification.v1.SendEmailResponse
}
var file_v1_notification_proto_depIdxs = []int32{
	1, // 0: notification.v1.SendPersonalizedEmailRequest.emails:type_name -> notification.v1.InfoPersonalizedRequest
	2, // 1: notification.v1.InfoPersonalizedRequest.detail:type_name -> notification.v1.DetailEmail
	4, // 2: notification.v1.SendCommonEmailRequest.emails:type_name -> notification.v1.InfoCommonRequest
	2, // 3: notification.v1.SendCommonEmailRequest.detail:type_name -> notification.v1.DetailEmail
	0, // 4: notification.v1.NotificationService.SendPersonalizedEmail:input_type -> notification.v1.SendPersonalizedEmailRequest
	3, // 5: notification.v1.NotificationService.SendCommonEmail:input_type -> notification.v1.SendCommonEmailRequest
	5, // 6: notification.v1.NotificationService.SendPersonalizedEmail:output_type -> notification.v1.SendEmailResponse
	5, // 7: notification.v1.NotificationService.SendCommonEmail:output_type -> notification.v1.SendEmailResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_notification_proto_init() }
func file_v1_notification_proto_init() {
	if File_v1_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_notification_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPersonalizedEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_notification_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoPersonalizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_notification_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetailEmail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_notification_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendCommonEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_notification_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoCommonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_notification_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_notification_proto_goTypes,
		DependencyIndexes: file_v1_notification_proto_depIdxs,
		MessageInfos:      file_v1_notification_proto_msgTypes,
	}.Build()
	File_v1_notification_proto = out.File
	file_v1_notification_proto_rawDesc = nil
	file_v1_notification_proto_goTypes = nil
	file_v1_notification_proto_depIdxs = nil
}
