// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: v1/template.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemplaterServiceClient is the client API for TemplaterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplaterServiceClient interface {
	Construct(ctx context.Context, in *ConstructRequest, opts ...grpc.CallOption) (*ConstructResponse, error)
}

type templaterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplaterServiceClient(cc grpc.ClientConnInterface) TemplaterServiceClient {
	return &templaterServiceClient{cc}
}

func (c *templaterServiceClient) Construct(ctx context.Context, in *ConstructRequest, opts ...grpc.CallOption) (*ConstructResponse, error) {
	out := new(ConstructResponse)
	err := c.cc.Invoke(ctx, "/template.v1.TemplaterService/Construct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplaterServiceServer is the server API for TemplaterService service.
// All implementations must embed UnimplementedTemplaterServiceServer
// for forward compatibility
type TemplaterServiceServer interface {
	Construct(context.Context, *ConstructRequest) (*ConstructResponse, error)
	mustEmbedUnimplementedTemplaterServiceServer()
}

// UnimplementedTemplaterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTemplaterServiceServer struct {
}

func (UnimplementedTemplaterServiceServer) Construct(context.Context, *ConstructRequest) (*ConstructResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Construct not implemented")
}
func (UnimplementedTemplaterServiceServer) mustEmbedUnimplementedTemplaterServiceServer() {}

// UnsafeTemplaterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplaterServiceServer will
// result in compilation errors.
type UnsafeTemplaterServiceServer interface {
	mustEmbedUnimplementedTemplaterServiceServer()
}

func RegisterTemplaterServiceServer(s grpc.ServiceRegistrar, srv TemplaterServiceServer) {
	s.RegisterService(&TemplaterService_ServiceDesc, srv)
}

func _TemplaterService_Construct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConstructRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplaterServiceServer).Construct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.v1.TemplaterService/Construct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplaterServiceServer).Construct(ctx, req.(*ConstructRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplaterService_ServiceDesc is the grpc.ServiceDesc for TemplaterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplaterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "template.v1.TemplaterService",
	HandlerType: (*TemplaterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Construct",
			Handler:    _TemplaterService_Construct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/template.proto",
}
